### ISSUE TITLE
[BUG] Month Text Blank on Training Requests

### ISSUE THREAD

**Issue by cdconn00** [zabartcc/issue-reporting#14]
## Describe the bug
![image](https://github.com/zabartcc/issue-reporting/assets/30357632/457e8a2e-204b-4538-a01d-0f104d8665bd)

## To Reproduce
1. Go to controller dashboard.
2. Click training requests.
3. Click one of the date fields.

## Expected behavior
You can see what month it is.

**Comment by cdconn00** [comment]
Triaged and added to backlog.

**Comment by XDerpingxGruntX** [comment]
Issue was fixed awhile back, never closed. Doesn't matter now as we have the new training site.
