### ISSUE TITLE
[BUG] Training requests/Time bug.

### ISSUE THREAD

**Issue by Wonderingg** [zabartcc/issue-reporting#15]
## Describe the bug
If my PC/device time is set to 18:00(or any other time) local time then it won't let me change it BEFORE the local time. Currently it is 18:00 in my local time and I can not select 17/16/15UTC because of the bug.

## To Reproduce
1. Go to 'Controller Dashboard.'
2. Click on 'Training Requests/Request.'
3. See error

## Expected behavior
Allows me to change the time to before the local time set on my device.

## Screenshots
![image](https://github.com/zabartcc/issue-reporting/assets/83306625/2335ab3e-1e8f-484e-810b-9ac5c65dec00)

## System Information (please complete the following information):
 - OS: [Windows 11]
 - Browser [Brave]

**Comment by cdconn00** [comment]
@Wonderingg Thanks for the issue. We'll take a look.

For triage: may be fixed by #2

**Comment by Wonderingg** [comment]
@cdconn00 Alright, good luck!
