### ISSUE TITLE
[FEATURE REQ] Manual Instructor Note Creation and Redirect

### ISSUE THREAD

**Issue by braukStauter** [zabartcc/issue-reporting#19]
## Describe the solution you'd like
Provide a means for an instructor to create training notes, independent of a training request put in by the student. 

I envision a button in the top-right corner of the "Training Sessions" page. When pressed a popup requests the name/CID of the student, that will generate a 1.5hour training session for that student and direct the instructor to the notes page to complete the session.

## Describe alternatives you've considered
N/A

## Is your feature request related to a problem? Please describe.
N/A

## Additional context
N/A

**Comment by cdconn00** [comment]
added to backlog

**Comment by XDerpingxGruntX** [comment]
Issue closed, new training site made by Ethan.
