### ISSUE TITLE
[FEATURE REQ] Display Requests in Users Local Time

### ISSUE THREAD

**Issue by cdconn00** [zabartcc/issue-reporting#2]
**Is your feature request related to a problem? Please describe.**
"User's local time instead of Zulu for everything. hides"

The user would like times for requests/etc in local time to avoid confusion.

**Describe the solution you'd like**
—

**Describe alternatives you've considered**
—

**Additional context**
https://discord.com/channels/506652179743113236/1021347324674453516

**Comment by cdconn00** [comment]
https://github.com/zabartcc/issue-reporting/issues/15 should be fixed by this. Posting here for visibility.

**Comment by cdconn00** [comment]
@c0repwn3r reassigned to you, move to in progress when you start work and let me know if you have questions.

**Comment by XDerpingxGruntX** [comment]
Issue closed, new training site.
