### ISSUE TITLE
[BUG] Training Notes Submission Error

### ISSUE THREAD

**Issue by braukStauter** [zabartcc/issue-reporting#20]
## Describe the bug
Certain training notes are not transmitted to VATUSA, following an error code is generally displayed "500"? I believe, at the time of submission.

## To Reproduce
1. Type Training Notes
2. (Has occurred at all drop-down box selections.) 
3. Press 'send to VATUSA'
4. Watch notifications in top right corner.

## Expected behavior
Training notes should be sent to VATUSA

## System Information (please complete the following information):
 - OS: Windows
 - Browser Chrome
 - Version Non-specific

## Additional context
N/A

**Comment by cdconn00** [comment]
note for developer: Id put money on this being an issue with the token we issue expiring after the vatsim oauth token expires. We may need to shorten the time our token is valid for.

**Comment by XDerpingxGruntX** [comment]
Issue closed, new training site made by Ethan.
