### ISSUE TITLE
[FEATURE REQ] Instructor Additions/Changes

### ISSUE THREAD

**Issue by braukStauter** [zabartcc/issue-reporting#21]
## Describe the solution you'd like
The entire training system is being revamped. There are several items in this one request to follow the project to completion. There are as follows:

1. A new data field will need to be added to controller profiles, “assigned instructor.” This data field will be editable on the controllers profile through the admin dashboard by TA, DTA, DATM, and ATM. The choices for assignable instructors should be pulled from the existing roster of both INSs and MTRs. 

2. The training requests page on the controller dashboard will need to be updated to reflect something similar to the following: 
![image](https://github.com/zabartcc/issue-reporting/assets/24839808/2048b5f6-6b6d-4b0f-b78d-6cfcacf52585) The “request” button (and feature on the student side) will be completely removed.
Wherein scheduled training (see the next bullet) will be listed. Clicking the assigned instructor box should link to either the controllers discord profile or ZAB email, to coordinate training sessions. 

3. Instructors/mentors needs the ability to schedule training sessions for their assigned students (basically create a “request” on behalf of the student, since it’ll probably be easier to use that existing infrastructure, but it will be initiated by the instructor and the student will not have access to request/schedule.)

4. An instructor’s training sessions will be listed as normal, with two new options: reschedule (which effectively just allows the instructor to change the date/time, and sends a notification email,) and no-show (which closes the session out internally with a “no-show” designator in the training record.)

**Comment by braukStauter** [comment]
So have the assigned instructor hyperlink to "discord.com/users/[ID]"

**Comment by braukStauter** [comment]
Additionally, we'll have to assign new members to instructors/mentors. They should be assigned to 
1. The instructor/mentor with the least number of students, and/or 
2. at random. 

The welcome email will need to be adjusted to note the assigned instructor. The assigned instructor should be CC'd on the email

**Comment by XDerpingxGruntX** [comment]
Issue closed, new training site completed by Ethan. Has most if not all features requested here.
