### ISSUE TITLE
[FEATURE REQ] Add Cancel Training Session Button 

### ISSUE THREAD

**Issue by cdconn00** [zabartcc/issue-reporting#5]
**Is your feature request related to a problem? Please describe.**
Mentors cannot cancel sessions.

**Describe the solution you'd like**
"plz add a cancel session button for mentors <3"

**Describe alternatives you've considered**
—

**Additional context**
—

**Comment by cdconn00** [comment]
Triaged, added to backlog.

**Comment by JWZABARTCC** [comment]
I'd like to talk about the expansion of this request.  I think there should also be some kind of "no-show" logic so we can separate a student cancel, an instructor cancel, and a student no-show.

**Comment by XDerpingxGruntX** [comment]
Issue closed, new training site made by Ethan covers this.
