### ISSUE TITLE
[FEATURE REQ] Allow Students to Change Training Request Times Before They Are 

### ISSUE THREAD

**Issue by cdconn00** [zabartcc/issue-reporting#6]
**Describe the solution you'd like**
"Allow controllers to edit the times on their training requests before the request has been taken, but after submission of the request."

**Comment by cdconn00** [comment]
Triaged, added to backlog.

**Comment by jonahkleinman** [comment]
can be closed with new training system

**Comment by XDerpingxGruntX** [comment]
Closed, new site made by Ethan.
