### ISSUE TITLE
[FEATURE REQ] Allow Training Admins to See Sessions that Have Been Picked Up

### ISSUE THREAD

**Issue by cdconn00** [zabartcc/issue-reporting#7]
**Describe the solution you'd like**
"Not sure if this should go here or instructor dashboard, but a way for the TA/DTA and Sr. Staff to see all sessions that have been picked up would be cool."

**Comment by cdconn00** [comment]
triaged, added to backlog.

**Comment by XDerpingxGruntX** [comment]
Issue closed, new training site by Ethan.
